name: smecv_grid
channels:
- defaults
dependencies:
- openssl=1.0.2k=1
- pip=9.0.1=py27_1
- pyflakes=1.5.0=py27_0
- python=2.7.13=0
- readline=6.2=2
- setuptools=27.2.0=py27_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py27_0
- zlib=1.2.8=3
- pytest=3.8.2
- pip:
  - autoflake==0.7
  - configparser==3.5.0
  - enum34==1.1.6
  - flake8==3.3.0
  - mccabe==0.6.1
  - netcdf4==1.2.7
  - numpy==1.12.1
  - pycodestyle==2.3.1
  - pygeogrids==0.2.2
  - pykdtree==1.2.1
  - pyproj==1.9.5.1
  - pytest-cov
